drop table if exists edw;
CREATE TABLE edw
(
    id  INTEGER  GENERATED BY DEFAULT AS IDENTITY,
    account_cd INTEGER ,
    agent_cd varchar(255)
--     client_lv_7 varchar(255),
--     revenue_amt varchar(255),
--     currency_cd varchar(255),
--     metric_type varchar(255),
--     src_system_cd varchar(255)
);